
public class AnagramTester {

    public static void testP1() {
        System.out.println("--- Testing p1() ---");
        
        String word = "hello";
        
        // Same as:
        // String[] possibleAnagrams = new String[3];
        // possibleAnagrams[0] = "cse8b";
        // possibleAnagrams[1] = "rocks";
        // possibleAnagrams[2] = "elloh";
        String[] possibleAnagrams = { "cse8b", "rocks", "elloh" };
        
        // We can use a try/catch statement to keep the program running even
        // when an exception is thrown.
        try {
            // This is how to call p1. p2 through p8 are called with the same
            // parameters.
            AnagramFinder.p1(possibleAnagrams, word);
            
        } catch (NullPointerException e) {
            // This code will execute if p1 throws a NullPointerException.
            System.out.println("An exception occurred! " + e.toString());
        }
        
        // This code will occur if try block executes successfully, or if the
        // exception is caught.
        System.out.println("-- Done testing p1() ---");
        
    }

    public static void testP2() {
        System.out.println("--- Testing p2() ---");

        String word = "hello";

        String[] possibleAnagrams = { "cse8b", "rocks", null };

        try {
            AnagramFinder.p2(possibleAnagrams, word);

        } catch (NullPointerException e) {
            System.out.println("An exception occurred! " + e.toString());
        }

        System.out.println("-- Done testing p2() ---");
   
    }
    public static void main(String[] args) {
        testP1();
        testP2();
    }
}
